export const Head = () => (
  <>
    <link
      href="/favicon.png"
      rel="icon"
      type="image/png"
    />
    <link
      href="/favicon.svg"
      rel="icon"
      type="image/svg+xml"
    />
    <link
      href="/styles.css"
      rel="stylesheet"
    />
    <link
      href="https://bigfundj.com"
      rel="preconnect"
    />
    <link
      href="https://ajax.googleapis.com"
      rel="preconnect"
    />
    <meta
      content="initial-scale=1,width=device-width"
      name="viewport"
    />
  </>
)
